### PR TITLE
Fixed composer.json to support SF3

### PR DESCRIPTION
**Pull request by boast**
Fixed missing "OR" version constraint for the `symfony/routing` component.

### CODE REVIEW

**Comment by boast** [comment]
See #224

**Comment by Ener-Getick** [comment]
Arf yeah thank you :+1:

**Comment by francoispluchino** [comment]
@Ener-Getick Maybe update the branch alias `1.5-dev` to `1.6-dev` (or `1.7-dev`?) because there is already an release `1.6.0` without the support of Symfony 3?

**Comment by Ener-Getick** [comment]
@francoispluchino done (see https://github.com/schmittjoh/JMSDiExtraBundle/commit/04161a9bdb419c6b88a31c78d62f245215fc7de6)

**Comment by francoispluchino** [comment]
@Ener-Getick Good! Again thank you for this port.

**Comment by Ener-Getick** [comment]
@francoispluchino you're welcome don't hesitate if you have any feedbacks :-)

**Comment by francoispluchino** [comment]
Yes, I'll test it on one of my projects tomorrow, I thinks.

**Comment by francoispluchino** [comment]
@Ener-Getick I just spent one of my projects with Symfony 3.0 (and this bundle) and everything is ok. A big thank you for your work.

**Pull request merged**
