### PR TITLE
Modify doctrine integration manner

### LINKED ISSUE #284: Container cache miss occurs on tests since Symfony 3.2.
Symfony 3.2 introduces a new config cache metadata [ClassExistenceResource](https://github.com/symfony/symfony/blob/edb8c33f35b981b72adbe23798753703edfe3819/src/Symfony/Component/Config/Resource/ClassExistenceResource.php).
It assumes the cache is not fresh when the class is added or lost since previous check.

If I enable the `doctrine_integration` config of this bundle, the proxy of EntityManager will be generated.
And the proxy would be assumed not to exist at the time of Kernel initializes container because it's only loaded when EntityManager is retrieved from container.

This thing has no problem on almost every HTTP requests, destroying the class existence info after request and 2nd check never happens.
However on the tests, the container will be initialized many times, it means container cache miss always occurs from 2nd test case which relies on Kernel and container.

It leads testsuite to be significant bad performance.

### PR DESCRIPTION
**Pull request by issei-m**
Fix #284

As I explained at above issue, current Doctrine integration way has issue that cache is invalidate every time on Symfony 3.3.
The direct cause of the problem seems to be DIC builder/compiler can't recognize EntityManager existence since it's never loaded unless it's not retrieved from built DIC itself.
And I sought out whether there's some workaround or not, but I could not.

However during I was looking down upon integration way around, I realized a fact that the tweaking EM of this bundle is just overriding its `getRepository`.
So I wanna introduce an another way of expanding this method here.

I repealed:

- Inheritance the EMs DoctrineBundle registered using CG package

And I changed:

- `ContainerAwareRepositoryFactoryDecorator`: implementing `RepositoryFactory` and wrapping the factory DoctrineBundle structured
  and doing integration with ORM something what this bundle was doing originally (using CG package)

**Drop support older (< 2.4) doctrine implicitly**

The RepositoryFactory of Doctrine/ORM capability was introduced in 2.4, so we cannot support compatibility with 2.3 (or older) anymore.

### CODE REVIEW

**Comment by greg0ire** [comment]
I'm trying to fix original CI in #289

**Comment by greg0ire** [comment]
It's merge, you my rebase (or simply closing and reopening should be enough)

**Comment by issei-m** [comment]
@greg0ire Thank you. I've done rebase.

**Comment by greg0ire** [comment]
It reveals you broke the tests. Please fix them.

**Comment by issei-m** [comment]
I'm starting to fix tests, so please wait for it ;)

**Comment by greg0ire** [comment]
I'm not in a hurry ;)

**Comment by issei-m** [comment]
I've done fixing the broken CI, so please reconsider it. Thanks.

**Pull request closed without merging**
