### PR TITLE
kernel is not actually needed

### PR DESCRIPTION
**Pull request by sam0delkin**
I found that kernel instance in Bundle constructor is used only for retreiving bundle paths, but it's not actually needed, because of containerBuilder has `kernel.bundles` parameter

### CODE REVIEW

**Comment by Ener-Getick** [comment]
:+1: can you rebase your PR on master please?

**Comment by sam0delkin** [comment]
@Ener-Getick what do you mean? This PR is already on the master branch and has no conflicts.

**Comment by Ener-Getick** [comment]
Yeah but I'd like to know if the new tests pass.

**Comment by sam0delkin** [comment]
@Ener-Getick done. And looks like tests passed.

**Comment by Ener-Getick** [comment]
Amazing thank you @sam0delkin !

**Pull request merged**
